# Generated by Django 5.0.6 on 2024-06-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_product_date_sold_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_sold',
        ),
    ]
